chore: verify that lower case tables config was correctly applied in new jobs

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -441,6 +441,15 @@ lint:
     - name: ${DB}
       alias: db
       command: ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_general_ci", "--lower-case-table-names=1"]
+  script:
+      # check that config table is stored lower case, i.e. the tests executed verify that lower case table names work.
+    - |
+      TABLES=$(python3 -c "from sqlalchemy import create_engine; print(*create_engine('$LINOTP_DATABASE_URI').table_names(), sep='\n')")
+      echo $TABLES
+      if [[ "$TABLES" =~ "Config" || ! "$TABLES" =~ "config" ]]; then
+        echo "ERROR: Expected to find table 'config' and not 'Config' in lower case table name tests."
+        exit 1
+      fi
 
 .postgres-database:
   extends:
@@ -558,6 +567,9 @@ functional-test-mysql-lower-case-table-names:
   extends:
     - .functional-test-base-dbs
     - .mysql-lower-case-table-names-database
+  script:
+    - !reference [".functional-test-base-dbs", "script"]
+    - !reference [".mysql-lower-case-table-names-database", "script"]
 
 .e2e-test:
   extends:
@@ -681,7 +693,9 @@ e2e-test-mysql-lower-case-table-names:
   services: 
     - !reference [".e2e-test-docker", "services"]
     - !reference [".mysql-lower-case-table-names-database", "services"]
-  # TODO: can we assert that tables are really lower case in this job?
+  script:
+    - !reference [".e2e-test-docker", "script"]
+    - !reference [".mysql-lower-case-table-names-database", "script"]
 
 # End to end test using Soft HSM image
 e2e-test-softhsm:
