feature: Change `/etc/linotp2` to `/etc/linotp` in many places.
Also remove various references to “LinOTP 2” in favour of just
“LinOTP”. A notable exception is the database configuration, which we
leave unchanged for compatibility with existing installations.

diff --git a/linotpd/src/debian/postrm b/linotpd/src/debian/postrm
--- a/linotpd/src/debian/postrm
+++ b/linotpd/src/debian/postrm
@@ -10,8 +10,8 @@ if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
     # Remove my changes to the db.
     db_purge
     if getent passwd linotp > /dev/null; then
-	if ! a2dissite linotp2; then
-	    echo `print_timestamp` "WARNING [linotp postrm] Could not disable Apache linotp2 host (possibly it doesn't exist)" >&2
+	if ! a2dissite linotp; then
+	    echo `print_timestamp` "WARNING [linotp postrm] Could not disable Apache linotp host (possibly it doesn't exist)" >&2
 	elif ! invoke-rc.d apache2 reload 2>/dev/null; then
 	    echo `print_timestamp` "WARNING [linotp postrm] Could not reload Apache (may not be a problem)"
 	fi
@@ -22,7 +22,7 @@ if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
     rm -fr /var/log/linotp
 
     # Where I come from, “purge” means purge.
-    rm -rf /etc/linotp2/*
+    rm -rf /etc/linotp/*
 fi
 
 #DEBHELPER#
