Don't break off package install/remove if a2dissite fails
When installing on UCS the 'linotp2' VirtualHost is not created by the
linotp package leading 'a2dissite linotp2' to fail.

The same applies to package removal. Additionally if someone removed
'linotp2' VirtualHost on a regular Debian installation before running
remove/purge then the removal would fail. This is now prevented, since
removing a package should always be allowed.

Change-Id: Ib3f91bf6f8af5579bdb3f758ea15a7d9758e5f14

diff --git a/linotpd/src/debian/postinst b/linotpd/src/debian/postinst
--- a/linotpd/src/debian/postinst
+++ b/linotpd/src/debian/postinst
@@ -394,7 +394,7 @@ configure)
 		invoke-rc.d apache2 reload
 		echo "LinOTP2: done setting up apache with ssl"
 	else
-		a2dissite linotp2
+		a2dissite linotp2 || echo `print_timestamp` "WARNING [linotp postinst] Could not disable Apache linotp2 host (possibly it doesn't exist)" >&2
 	fi
 
 	########################################################################
diff --git a/linotpd/src/debian/prerm b/linotpd/src/debian/prerm
--- a/linotpd/src/debian/prerm
+++ b/linotpd/src/debian/prerm
@@ -2,6 +2,10 @@
 
 . /usr/share/debconf/confmodule
 
+print_timestamp() {
+	date +"%Y/%m/%d - %T"
+}
+
 # check if linotp was run via apache
 db_get linotp/apache/activate || true
 
@@ -13,7 +17,7 @@ if [ ! -f /etc/apache2/sites-enabled/linotp2 ] &&
 fi
 
 if [ "$RET" = "true" ]; then
-	a2dissite linotp2
+	a2dissite linotp2 || echo `print_timestamp` "WARNING [linotp prerm] Could not disable Apache linotp2 host (possibly it doesn't exist)" >&2
 	invoke-rc.d apache2 reload
 fi
 
