Add Debian "stretch" packaging changes for main LinOTP package.
Here again we're doing the straightforward parts of adapting the
Debian packaging for the linotp package to Debian stretch.

  - python-support is replaced by dh-python (pybuild).

  - Apart from this, the most notable change is probably that
    hard-coded version numbers in the Debian configuration
    files (other than "changelog") have been removed; they will be
    filled in when the package is assembled using the most recent
    entry in the Debian changelog.

  - The linotp package "Provides:" linotp-useridresolver and
    linotp-smsprovider since this functionality is now part of the
    linotp package, rather than separate packages.

  - The setuptools install process places some files in /usr/etc
    that should really go to /etc. This is also rectified in the
    rules file.

  - Support for Python 2.6 is dropped.

  - We're using "invoke-rc.d" to run the init script, and include
    some other courtesies so the package plays more nicely with
    systemd.

See LINOTP-497, LINOTP-498, LINOTP-499, LINOTP-500, LINOTP-507.

Change-Id: I4c12513c4f4852de1c7b04f3f15aedfcebae676a

diff --git a/linotpd/src/debian/postrm b/linotpd/src/debian/postrm
--- a/linotpd/src/debian/postrm
+++ b/linotpd/src/debian/postrm
@@ -10,10 +10,13 @@ if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
     # Remove my changes to the db.
     db_purge
     if getent passwd linotp > /dev/null; then
-		a2dissite linotp2 || echo `print_timestamp` "WARNING [linotp postrm] Could not disable Apache linotp2 host (possibly it doesn't exist)" >&2
-	    echo "Deleting user >>linotp<<"
-	    deluser linotp 
-		/etc/init.d/apache2 reload
+	if ! a2dissite linotp2; then
+	    echo `print_timestamp` "WARNING [linotp postrm] Could not disable Apache linotp2 host (possibly it doesn't exist)" >&2
+	elif systemctl is-active -q apache2; then
+	    invoke-rc.d apache2 reload
+	fi
+	echo "Deleting user >>linotp<<"
+	deluser linotp
     fi
     echo "Deleting log directory."
     rm -fr /var/log/linotp
